# HIF (High Efficiency Image Format)
ext hif = feh --scale-down --auto-zoom -- $@

# MOV (Video files)
ext mov = mpv --loop-file=inf -- $@

# RAF (Fujifilm RAW files)
ext raf = exiftool -previewImage -b $1 | feh -
