import = [
    "~/.config/alacritty/colorscheme.toml"
]
live_config_reload = true

[font]
size = 12.5
[font.normal]
family = "ShureTechMono Nerd Font"

[window]
opacity = 0.5
dynamic_padding = true
[window.padding]
x = 0
y = 0

[bell]
animation = "EaseOut"
color = "#7555FF"
duration = 200

[cursor]
blink_timeout = 0
blink_interval = 550
[cursor.style]
shape = "Block"
blinking = "On"

[mouse]
hide_when_typing = true
